method: unsloth
unsloth_settings:
  load_in_4bit: false
  max_seq_length: 2048
  dtype: "bfloat16"

peft:
  r: 16
  lora_alpha: 16
  lora_dropout: 0
  bias: "none"
  random_state: 3407

trainer:
  dataset_text_field: "text"
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 100
  learning_rate: 0.00005
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  output_dir: "outputs"
